### ISSUE TITLE
test only one image

### ISSUE THREAD

**Issue by Ariel-JUAN** [fangchangma/sparse-to-dense#10]
Hi, thanks for sharing the great work. 
I would like to test one image using the pretrained kitti model.  I am not familiar with the lua. Can you tell me how to change the code? Thanks!

**Comment by fangchangma** [comment]
Hi. The current test function is implemented in https://github.com/fangchangma/sparse-to-dense/blob/67a9a95f7f199f1dce183ef860071dadc6d2bf8b/train.lua#L115

You can replicate the Trainer:test() function with your own the dataloader.

**Comment by yechenw** [comment]
Hi, is it possible to visualize the predicted depth map based on a trained model? I'm not familiar with lua too. Thanks!

**Comment by fangchangma** [comment]
> Hi, is it possible to visualize the predicted depth map based on a trained model? I'm not familiar with lua too. Thanks!

It might be possible to visualize them using the command `itorch.image()`. For instance, see [here](https://github.com/facebookarchive/iTorch/blob/master/screenshots/image.png). 

(P.S. please create issues for new questions)
