### ISSUE TITLE
About the torch version performance

### ISSUE THREAD

**Issue by gfl699468** [fangchangma/sparse-to-dense#11]
Hi, thanks for sharing the torch code, it's a brilliant work, however, when I use the setting indicated from the released trained result path:
sparse-to-dense/results/nyudepthv2.input=rgbd.nsample=200.rep=linear.encoder=conv.decoder=upproj.criterion=l1.lr=0.01.bs=16.pretrained=true

which is:
th main.lua -dataset nyudepthv2 -inputType rgbd -nSample 200 -criterion l1 -encoderType conv -decoderType upproj -pretrain true -b 16 --lr 0.01

the model's performance on the test dataset is:

MSE=0.084
RMSE=0.239
MAE=0.132
DELTA1=0.970
DELTA2=0.993
DELTA3=0.998
REL=0.046
LG10=nan
runtime(per image)=35.380ms

the released model's performance is:

MSE=0.073
RMSE=0.227
MAE=0.122
DELTA1=0.972
DELTA2=0.994
DELTA3=0.998
REL=0.044
LG10=nan
runtime(per image)=35.828ms

Looks like there is a small gap between two models' performance, is there something I am missing?

**Comment by fangchangma** [comment]
Hi. The command is correct, and the performance is in fact quite close. The small gap might be due to randomness in both weight initialization and SGD during training. You might be able to get a slightly better result if you train for a second time.

**Comment by gfl699468** [comment]
Ok, I will try that, thanks for your reply!
