### ISSUE TITLE
Question regarding dataset resolution

### ISSUE THREAD

**Issue by ShreyasSkandan** [fangchangma/sparse-to-dense#13]
If I read correctly, you use the KITTI odometry dataset in training this network.

I noticed that some image sequences in your hdf5 folder are of different dimensions than others. Pardon my ignorance if this is identical to the original dataset. If not, is there a reason for resizing them?

For example,

Sequence 03 is 1242x375, Sequence 00 is 1241x376, Sequence 04 is 1226x370 etc.

Thanks in advance, sorry if the answer to this is an obvious one.

Best regards,
Shreyas

**Comment by fangchangma** [comment]
Hi Shreyas. The difference in sizes comes from the original dataset. In particular, I used the rectified images, and

> The size of the images after rectification depends on the calibration parameters

 see Section III.A (a) in the KITTI paper [Vision meets Robotics: The KITTI Dataset](http://www.cvlibs.net/publications/Geiger2013IJRR.pdf)

**Comment by ShreyasSkandan** [comment]
Great, thank you very much for the quick response. That makes complete sense now.
