### ISSUE TITLE
question about test:

### ISSUE THREAD

**Issue by angelbeibei** [fangchangma/sparse-to-dense#14]
Hi,when i run th main.lua -testOnly true -dataset nyudepthv2 -inputType rgbd -nSample 200 -criterion l1 -encoderType conv -decoderType upproj -pretrain true
and then i met this error, can you help me?

/home/zhangwei/torch/install/bin/luajit: ...zhangwei/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 2 callback] bad argument #2 to '?' (dimension 1 out of range of 0D tensor at /home/zhangwei/torch/pkg/torch/generic/Tensor.c:19)
stack traceback:
	[C]: at 0x7f7b3ebbf1e0
	[C]: in function 'xpcall'
	...zhangwei/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	...e/zhangwei/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...e/zhangwei/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	...e/zhangwei/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	...zhangwei/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	...zhangwei/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	...zhangwei/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
	...zhangwei/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
	./dataloader.lua:47: in function '__init'
	/home/zhangwei/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/zhangwei/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataLoader'
	./dataloader.lua:26: in function 'create'
	main.lua:30: in main chunk
	[C]: in function 'dofile'
	...gwei/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by fangchangma** [comment]
I'm not sure what the problem was. Did you download both the data and the trained models?
