### ISSUE TITLE
question about pretrained model (Resnet)

### ISSUE THREAD

**Issue by polar99** [fangchangma/sparse-to-dense#15]
Thanks for releasing the source code! Your work is excellent!
I have run your code (using default settings) these days on nyudepthv2. 
But I found that I got the best result **delta<1.25 =0.64** (in paper it is 0.81). 
I did not use the pretrained model of ResNet. Is it the reason?
@fangchangma

**Comment by fangchangma** [comment]
Hi. Yes, not using the pretrained weights leads to suboptimal performance.

**Comment by polar99** [comment]
Thank you! I run the code with pretrained model and got a better performance (delta<1.25 =0.8093) which is very closed to the best results.
