### ISSUE TITLE
Could it be used for live depth map generation?

### ISSUE THREAD

**Issue by JeyP4** [fangchangma/sparse-to-dense#16]
Hi @fangchangma 

Using good RGB camera and solid-state Lidar, could it be used for live applications also?

If yes, considering a good computer system(say i7-8cores | GeForce GTX 1050 Ti) what additional latency it may result?

Thanks for consideration.

**Comment by fangchangma** [comment]
Hi. I believe so. With a decent desktop GPU, the runtime can easily achieve 100+ fps, depending on which encoder/decoder you use.

Our recent ICRA'19 paper on "FastDepth: Fast Monocular Depth Estimation on Embedded Systems" addresses the latency issues specifically for embedded systems. The paper will be released on arXiv soon.

**Comment by JeyP4** [comment]
Thanks for replying. 
Are you talking about jpeg encoder/decoder.
Which one is recommended by you?

**Comment by fangchangma** [comment]
No, I was referring to the encoder/decoder in the neural network structure.
