### ISSUE TITLE
Can't download datasets

### ISSUE THREAD

**Issue by ecervera** [fangchangma/sparse-to-dense#19]
I try to download a dataset from
http://datasets.lids.mit.edu/sparse-to-dense/data/nyudepthv2.tar.gz 
but only ~4 GBs are sent, then the connection slows down and finally stops working. Wondering if there is a problem with the server disk.
Thanks.

**Comment by fangchangma** [comment]
Our server might have been down for a short period of time. We just checked downloading the dataset and it seemed to be working fine now. Please try again.

**Comment by ecervera** [comment]
Thanks, now it worked!

**Comment by whubaichuan** [comment]
@ecervera @fangchangma Hi, the download speed (13kb/s ) is too low when I use the command "wget http://datasets.lids.mit.edu/sparse-to-dense/data/nyudepthv2.tar.gz". How can I raise the download speed?
