### ISSUE TITLE
where to get pretrained model for kitti dataset?

### ISSUE THREAD

**Issue by mylxiaoyi** [fangchangma/sparse-to-dense#2]
Thanks for sharing your perfect job.

but where can i get the pretrained model for kitti dataset?

thanks.

**Comment by fangchangma** [comment]
I released two trained models in http://datasets.lids.mit.edu/sparse-to-dense/results/. 

The file size for KITTI is larger than it should be, since I forgot to clean up the model before saving. However that shouldn't hurt.

**Comment by mylxiaoyi** [comment]
Thanks, i will have a try.

**Comment by whubaichuan** [comment]
@mylxiaoyi Hi, the download speed (13kb/s ) is too low when I use the command "wget http://datasets.lids.mit.edu/sparse-to-dense/data/nyudepthv2.tar.gz" even in VPN mode. How can I raise the download speed? Looking forward to your reply.
