### ISSUE TITLE
When the pytorch version will be released?

### ISSUE THREAD

**Issue by duanyongli** [fangchangma/sparse-to-dense#3]
I'm very interested in your perfect work. But I'm really not interested in Lua.
Do you have schedule to complete the pytorch version?

**Comment by fangchangma** [comment]
Hi @duanyongli. I plan to release the pytorch version by Feb 20.

**Comment by Ariel-JUAN** [comment]
Hi~ do you have schedule to complete the TensorFlow version? It will be really exciting!

**Comment by fangchangma** [comment]
> Hi~ do you have schedule to complete the TensorFlow version? It will be really exciting!

Hi. Currently I don't have any plan to migrate to TensorFlow. However, it should be rather straightforward to migrate to TensorFlow from PyTorch.

**Comment by fangchangma** [comment]
The PyTorch version is in [https://github.com/fangchangma/sparse-to-dense.pytorch.git](https://github.com/fangchangma/sparse-to-dense.pytorch.git) (ongoing development)

**Comment by fangchangma** [comment]
Just released the PyTorch code.
