### ISSUE TITLE
About using resnet model pretrained on imagetNet.

### ISSUE THREAD

**Issue by chenchr** [fangchangma/sparse-to-dense#4]
Hello. Thank you for releasing the code. I read your paper, and found that you used resnet model pretrained on imagetNet. However, as the model trained on imageNet should have input channels as 3 at first laye, when turning to training ```sparse to dense``` with rgbd data as input, the input channels become 4. How to deal with this problem? Thanks!

**Comment by fangchangma** [comment]
Hi. The first convolution layer is not from the imageNet-pretrained model but instead trained from scratch.
https://github.com/fangchangma/sparse-to-dense/blob/5994c396ad70d0e1c22f9c985df117edc0348f78/models/resnet-kitti.lua#L226
