### ISSUE TITLE
Using this model on stereo images.

### ISSUE THREAD

**Issue by chan-e91** [fangchangma/sparse-to-dense#5]
Hi fangchangma,
Thanks for great article.

I want to use this method to calculate depth map from left and right images taken from a stereo camera.
Can i directly use the pre-trained mobilenet model on my dataset of left and right images.
Also, how the images should be given, if we want to train this model using my left and right images.

**Comment by fangchangma** [comment]
> I want to use this method to calculate depth map from left and right images taken from a stereo camera.
> Can i directly use the pre-trained mobilenet model on my dataset of left and right images.
> Also, how the images should be given, if we want to train this model using my left and right images.

If I understand correctly, you wanted to do feature matching using stereo images to get sparse triangulated depth, and then use these sparse depth to predict a dense depth image?

**Comment by chan-e91** [comment]
Yes, my main objective is to calculate the distance to obstacle after
getting the depth map, created using the stereo images.
So I have created a dataset of the left and right stereo images.
I want to apply your algorithm on these images to get depth map.
Thanks.

**Comment by fangchangma** [comment]
I see. This indeed has been one of the targeting applications of our approach. The only difference from the current code is to use sparse depth samples from stereo images, rather than uniform random samples from ground truth. 

The fastest way to approach this problem (assuming you have the ground truth disparity images) would be 
- as a pre-processing step, do feature matching and triangulation of the stereo images to get the sparse depth samples, and save them to files (e.g., in hdf5 format).
- modify the dataloader such that it loads the sparse depth and color images the input, and the ground truth depth as target.
- train the model.

**Comment by chan-e91** [comment]
Hi,
Thank you.
I currently do not have ground truth disparity images, I will try to create
them. And follow the steps you have listed.
Also after training, can we implement this on live data(like data coming
from a stereo camera, mounted on a moving car )  ?


On Mar 14, 2018 11:36 PM, "Fangchang Ma" <notifications@github.com> wrote:

I see. This indeed has been one of the targeting applications of our
approach. The only difference from the current code is to use sparse depth
samples from stereo images, rather than uniform random samples from ground
truth.

The fastest way to approach this problem (assuming you have the ground
truth disparity images) would be

   - as a pre-processing step, do feature matching and triangulation of the
   stereo images to get the sparse depth samples, and save them to files
   (e.g., in hdf5 format).
   - modify the dataloader such that it loads the sparse depth and color
   images the input, and the ground truth depth as target.
   - train the model.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fangchangma/sparse-to-dense/issues/5#issuecomment-373120414>,
or mute the thread

**Comment by fangchangma** [comment]
I believe so. With a decent GPU (e.g., Titan X), the inference can easily run at 50Hz or above. Even with a embedded GPU (e.g. Jetson TX2) you should be able to run at around 15Hz.

**Comment by chan-e91** [comment]
Thanks Ma,
I will try to build up pre-requisites as you have said.
