### ISSUE TITLE
unable to run the code on nyudepthv2 dataset.

### ISSUE THREAD

**Issue by chan-e91** [fangchangma/sparse-to-dense#7]
Hi,
I have setup the torch environment as suggested by you and downloaded the datasets.
But when i try to run the training step, error is raised as shown below

![cutorch](https://user-images.githubusercontent.com/30966171/37280424-ba621b40-2613-11e8-960f-de95faa42e4f.png)
Can you please identify, what is wrong with the code ?
Thanks in advance .

**Comment by fangchangma** [comment]
Hello. What's the command you used and how large is your GPU memory? You probably got the error because your GPU memory was maxed out. Try using a simpler upsampling layer (e.g., `-decoderType deconv2`) and a smaller batch size (e.g., `-batchSize 8`).

**Comment by chan-e91** [comment]
Hi,
Yes, as you said my GPU memory maxed out. I will try to implement your
suggestions.
